### ISSUE TITLE
Cannot push because of "cURL: 60 SSL" error.

### ISSUE THREAD

**Issue by mjbezer** [Elendev/nexus-composer-push#47]
I did a push, but it is returning an error:

```
[GuzzleHttp\Exception\RequestException]                                                                                                                               
  cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://nexus.(...)
```

Include "config" in composer.json, but apparently it had no effect

```
 "config": {
        "secure-https":false
    },

```
What can I do?

**Comment by Elendev** [comment]
Hello @mjbezer,

That's a good point, currently the plugin doesn't take in account this parameter. You can either propose a PR with a fix, or wait until I've refactored part of the code and integrated this.
It should be fixed in a few days if everything goes as expected.

Sorry for the inconvenience
